# Generated by Django 4.2.14 on 2024-08-02 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_user_max_otp_try_remove_user_otp_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="is_verified",
            new_name="isverified",
        ),
    ]
