# Generated by Django 4.2.14 on 2024-08-02 05:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_rename_is_verified_user_isverified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be 10 digits only.",
                        regex="^\\d{10}$",
                    )
                ],
            ),
        ),
    ]
