# Generated by Django 4.2.14 on 2024-08-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_remove_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="company_name",
            field=models.CharField(default="abc", max_length=50),
        ),
        migrations.AddField(
            model_name="user",
            name="designation",
            field=models.CharField(default="abc", max_length=50),
        ),
    ]
