# Generated by Django 4.2.14 on 2024-08-29 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_company_name_user_designation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
