# Generated by Django 4.2.14 on 2024-07-29 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='assigned_users',
            field=models.ManyToManyField(related_name='assigned_clients', to='users.user'),
        ),
        migrations.AddField(
            model_name='product',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='clients.client'),
        ),
        migrations.AddField(
            model_name='product',
            name='use_cases',
            field=models.ManyToManyField(related_name='products', to='clients.usecase'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='prospect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.prospect'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
