# Generated by Django 4.2.14 on 2024-09-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='additional_emails',
            field=models.TextField(blank=True, help_text='Comma-separated list of additional emails.', null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='meeting_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
