# Generated by Django 4.2.14 on 2024-08-08 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prospect",
            name="use_cases",
        ),
    ]
