# Generated by Django 4.2.14 on 2024-08-08 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0003_remove_prospect_use_cases"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="use_cases",
        ),
        migrations.AddField(
            model_name="usecase",
            name="product",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usecases",
                to="clients.product",
            ),
        ),
    ]
