# Generated by Django 4.2.14 on 2024-08-09 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clients", "0005_product_address_product_description_product_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IdealCustomerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "industry",
                    models.CharField(
                        choices=[("Tech", "Technology"), ("Health", "Healthcare")],
                        help_text="Select the industry",
                        max_length=50,
                    ),
                ),
                (
                    "geography",
                    models.CharField(
                        choices=[("NA", "North America"), ("EU", "Europe")],
                        help_text="Select the geographical region",
                        max_length=50,
                    ),
                ),
                (
                    "company_size",
                    models.CharField(
                        choices=[
                            ("Small", "1-50 employees"),
                            ("Medium", "51-200 employees"),
                            ("Large", "201+ employees"),
                        ],
                        help_text="Select the size of the company",
                        max_length=50,
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("HR", "Human Resources"),
                            ("IT", "Information Technology"),
                        ],
                        help_text="Select the department",
                        max_length=50,
                    ),
                ),
                (
                    "designations",
                    models.TextField(help_text="Comma-separated designations"),
                ),
                (
                    "additional_details",
                    models.TextField(
                        blank=True,
                        help_text="Additional details about the ideal customer profile",
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QualifyingQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="QualifyingQuestionResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("response", models.TextField()),
                (
                    "qualifying_question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clients.qualifyingquestion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "link",
                    models.URLField(
                        help_text="Link to resources like websites, documents, etc."
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="downloadableresource",
            name="product",
        ),
        migrations.RemoveField(
            model_name="referencesite",
            name="product",
        ),
        migrations.RemoveField(
            model_name="video",
            name="product",
        ),
        migrations.RemoveField(
            model_name="product",
            name="address",
        ),
        migrations.RemoveField(
            model_name="product",
            name="email",
        ),
        migrations.RemoveField(
            model_name="product",
            name="linkedin_url",
        ),
        migrations.RemoveField(
            model_name="product",
            name="location",
        ),
        migrations.RemoveField(
            model_name="product",
            name="logo_url",
        ),
        migrations.RemoveField(
            model_name="product",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="product",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="product",
            name="website_url",
        ),
        migrations.RemoveField(
            model_name="prospect",
            name="product",
        ),
        migrations.RemoveField(
            model_name="usecase",
            name="product",
        ),
        migrations.AddField(
            model_name="client",
            name="company_description",
            field=models.TextField(
                help_text="A brief description of the company.", null=True
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="company_website",
            field=models.URLField(
                help_text="The official website of the company.", null=True
            ),
        ),
        migrations.AddField(
            model_name="meeting",
            name="other_relevant_details",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="meeting",
            name="poc_designation",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="meeting",
            name="poc_email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="meeting",
            name="poc_first_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="meeting",
            name="poc_last_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="meeting",
            name="poc_phone_number",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="meeting",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Scheduled"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("rescheduled", "Rescheduled"),
                ],
                default="scheduled",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="meeting",
            name="use_cases",
            field=models.ManyToManyField(related_name="meetings", to="clients.usecase"),
        ),
        migrations.AddField(
            model_name="product",
            name="key_features",
            field=models.TextField(
                help_text="Key product features in bullet points", null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="key_problems_solved",
            field=models.TextField(
                help_text="Key problems solved by the product in bullet points",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="product_prospects",
            field=models.ManyToManyField(related_name="product", to="clients.prospect"),
        ),
        migrations.AddField(
            model_name="product",
            name="use_cases",
            field=models.ManyToManyField(related_name="products", to="clients.usecase"),
        ),
        migrations.AddField(
            model_name="usecase",
            name="title",
            field=models.CharField(default=1, max_length=255),
        ),
        migrations.AlterField(
            model_name="client",
            name="calendly_link",
            field=models.URLField(
                help_text="Link to the company's Calendly schedule.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(help_text="Brief product description", null=True),
        ),
        migrations.AlterField(
            model_name="usecase",
            name="description",
            field=models.TextField(help_text="Brief description of the use case"),
        ),
        migrations.DeleteModel(
            name="ActionButton",
        ),
        migrations.DeleteModel(
            name="DownloadableResource",
        ),
        migrations.DeleteModel(
            name="ReferenceSite",
        ),
        migrations.DeleteModel(
            name="Video",
        ),
        migrations.AddField(
            model_name="meeting",
            name="qualifying_question_responses",
            field=models.ManyToManyField(
                related_name="meetings", to="clients.qualifyingquestionresponse"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="ideal_customer_profiles",
            field=models.ManyToManyField(
                related_name="products", to="clients.idealcustomerprofile"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="qualifying_questions",
            field=models.ManyToManyField(
                related_name="products", to="clients.qualifyingquestion"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="resources",
            field=models.ManyToManyField(
                related_name="products", to="clients.resource"
            ),
        ),
    ]
