# Generated by Django 4.2.14 on 2024-08-11 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0006_idealcustomerprofile_qualifyingquestion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usecase",
            name="reference_links",
            field=models.TextField(
                help_text="Reference links related to the use case", null=True
            ),
        ),
        migrations.AddField(
            model_name="usecase",
            name="sample_pitch",
            field=models.TextField(
                help_text="Sample pitch to present the use case", null=True
            ),
        ),
        migrations.AddField(
            model_name="usecase",
            name="solution",
            field=models.TextField(
                help_text="How the product is solving the problem", null=True
            ),
        ),
        migrations.AddField(
            model_name="usecase",
            name="target_audience",
            field=models.TextField(
                help_text="Who might be facing the problem?", null=True
            ),
        ),
        migrations.AlterField(
            model_name="usecase",
            name="description",
            field=models.TextField(
                help_text="Brief description of the use case", null=True
            ),
        ),
    ]
