# Generated by Django 4.2.14 on 2024-08-11 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0007_usecase_reference_links_usecase_sample_pitch_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="company_profile",
        ),
        migrations.AddField(
            model_name="client",
            name="company_logo",
            field=models.ImageField(
                blank=True,
                help_text="Upload the company logo.",
                null=True,
                upload_to="company_logos/",
            ),
        ),
    ]
