# Generated by Django 4.2.14 on 2024-08-14 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0008_remove_client_company_profile_client_company_logo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prospect",
            name="designation",
        ),
        migrations.RemoveField(
            model_name="prospect",
            name="email",
        ),
        migrations.RemoveField(
            model_name="prospect",
            name="is_locked",
        ),
        migrations.RemoveField(
            model_name="prospect",
            name="linkedin_id",
        ),
        migrations.RemoveField(
            model_name="prospect",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="prospect",
            name="poc_first_name",
        ),
        migrations.RemoveField(
            model_name="prospect",
            name="poc_last_name",
        ),
        migrations.AddField(
            model_name="prospect",
            name="geography",
            field=models.CharField(
                default="Undefined",
                help_text="Geographic location of the prospect",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="prospect",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Meeting Scheduled"),
                    ("completed", "Meeting Completed"),
                    ("closed", "Deal Closed"),
                    ("open", "Open For Meeting"),
                ],
                default="open",
                help_text="Current status of the prospect",
                max_length=50,
            ),
        ),
    ]
