# Generated by Django 4.2.14 on 2024-08-15 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_user_company_name_user_designation"),
        ("clients", "0009_remove_prospect_designation_remove_prospect_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meeting",
            name="completed",
        ),
        migrations.RemoveField(
            model_name="meeting",
            name="is_successful",
        ),
        migrations.AlterField(
            model_name="meeting",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.user"
            ),
        ),
    ]
