# Generated by Django 4.2.14 on 2024-08-18 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_remove_meeting_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.product'),
        ),
    ]
