# Generated by Django 4.2.14 on 2024-08-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_meeting_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('closed', 'Closed')], default='scheduled', max_length=20),
        ),
    ]
