# Generated by Django 4.2.14 on 2024-08-21 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_company_name_user_designation'),
        ('clients', '0012_alter_meeting_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poc_first_name', models.CharField(max_length=255)),
                ('poc_last_name', models.CharField(max_length=255)),
                ('poc_email', models.EmailField(max_length=254)),
                ('poc_designation', models.CharField(max_length=255)),
                ('email_subject', models.CharField(max_length=255)),
                ('email_body', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.prospect')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
