# Generated by Django 4.2.14 on 2024-08-21 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_emailrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailrequest',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.product'),
        ),
    ]
