# Generated by Django 4.2.14 on 2024-08-23 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0018_alter_client_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='user',
            new_name='client',
        ),
    ]
