# Generated by Django 4.2.14 on 2024-08-23 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0019_rename_user_otp_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
