# Generated by Django 4.2.14 on 2024-08-25 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_company_name_user_designation'),
        ('clients', '0020_prospect_is_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, related_name='assigned_clients', to='users.user'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ideal_customer_profiles',
            field=models.ManyToManyField(blank=True, related_name='products', to='clients.idealcustomerprofile'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_prospects',
            field=models.ManyToManyField(blank=True, related_name='product', to='clients.prospect'),
        ),
        migrations.AlterField(
            model_name='product',
            name='qualifying_questions',
            field=models.ManyToManyField(blank=True, related_name='products', to='clients.qualifyingquestion'),
        ),
        migrations.AlterField(
            model_name='product',
            name='use_cases',
            field=models.ManyToManyField(blank=True, related_name='products', to='clients.usecase'),
        ),
    ]
