# Generated by Django 4.2.14 on 2024-08-28 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0021_alter_product_assigned_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video_link',
            field=models.URLField(blank=True, help_text='Link to the product video', null=True),
        ),
    ]
