# Generated by Django 4.2.14 on 2024-08-29 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0022_product_video_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Meeting Scheduled'), ('completed', 'Meeting Completed'), ('closed', 'Deal Closed'), ('open', 'Open For Meeting'), ('pending', 'Pending For Approval')], default='open', help_text='Current status of the prospect', max_length=50),
        ),
    ]
